### ISSUE TITLE
TypeError: done is not a function

### ISSUE THREAD

**Issue by ernestasromeika** [shobrook/BitVision#234] opened 2019-01-16 19:15 UTC
`TypeError: done is not a function`
Happens when entering bitstamp username/api key. 
OS: Windows 10
Node: v10.13.0
Python: 3.7.2

Other strange (perhaps related) behaviour:
Everytime on startup I'm asked this:
`You are missing the following dependencies: realtime-talib, sklearn. Would you like to install them?`
and every time I choose "yes", perhaps it experiences some issues installing one of these?
Also, when typing in the login details every letter appears 8 times.

`
TypeError: done is not a function
    at Textbox.Textarea._listener (...\AppData\Roaming\npm\node_modules\bitvision\node_modules\blessed\lib\widgets\textarea.js:231:5)
    at Textbox._listener (...\AppData\Roaming\npm\node_modules\bitvision\node_modules\blessed\lib\widgets\textbox.js:43:15)
    at Textbox.EventEmitter._emit (...\AppData\Roaming\npm\node_modules\bitvision\node_modules\blessed\lib\events.js:98:20)
    at Textbox.EventEmitter.emit (...\AppData\Roaming\npm\node_modules\bitvision\node_modules\blessed\lib\events.js:117:12)
    at Form.<anonymous> (...\AppData\Roaming\npm\node_modules\bitvision\node_modules\blessed\lib\widgets\form.js:43:14)
    at Form.EventEmitter._emit (...\AppData\Roaming\npm\node_modules\bitvision\node_modules\blessed\lib\events.js:94:20)
    at Textbox.EventEmitter.emit (...\AppData\Roaming\npm\node_modules\bitvision\node_modules\blessed\lib\events.js:131:12)
    at Program.<anonymous> (...\AppData\Roaming\npm\node_modules\bitvision\node_modules\blessed\lib\widgets\screen.js:602:15)
    at Program.emit (events.js:182:13)
    at ...\AppData\Roaming\npm\node_modules\bitvision\node_modules\blessed\lib\program.js:410:15
PS ...>
`

**Comment by RED29** [comment] 2019-01-16 23:53
I had the same error on mac. I resolve it by installing this:
For realtime-talib:
Mac OS X
$ brew install ta-lib 
$ pip3 install realtime_talib

For sklearn:
$ pip3 install scipy
$ pip3 install scikit-learn

After that the type error disappear and you can type your codes.

**Comment by corsa** [comment] 2019-01-17 20:44
Thanks for the workaround, copying the .json files now enable Bitvision to launch, but now I'm getting the same problem someone posted in issue #230 .

**Comment by alichtman** [comment] 2019-01-17 21:30
I've never seen these issues before, and I can't reproduce them on my machine.

Can anyone provide some more information to help debug this? (OS versions, node versions, python versions, pip3 versions, pip3 install lists, etc)

**Comment by corsa** [comment] 2019-01-17 21:41
Sure, for me:
macOS Mojave 10.14.2
Node v11.6.0 and v10.15.0 (have tried it under both)
Python version 3.7.2
pip3 version 18.1
pip3 list:
`arrow           0.13.0    
beautifulsoup4  4.7.1     
bs4             0.0.1     
certifi         2018.11.29
chardet         3.0.4     
dateparser      0.7.0     
idna            2.8       
moment          0.8.2     
nltk            3.4       
numpy           1.16.0    
pandas          0.23.4    
pip             18.1      
python-crontab  2.3.6     
python-dateutil 2.7.5     
pytz            2018.9    
realtime-talib  0.25      
regex           2018.11.22
requests        2.21.0    
scikit-learn    0.20.2    
scipy           1.2.0     
setuptools      40.6.3    
singledispatch  3.4.0.3   
six             1.12.0    
sklearn         0.0       
soupsieve       1.7.1     
TA-Lib          0.4.17    
textblob        0.15.2    
times           0.7       
tzlocal         1.5.1     
urllib3         1.24.1    
wheel           0.32.3 `

I had to install ta-lib via brew then installed realtime-talib via pip3. I also had to manually download all the .json files under store except config.json, that was the only file that was already in that directory.
I'm now having the same issues as #230 where the UI shows no data, and I get those errors if I hit the "h" key for help.

**Comment by alichtman** [comment] 2019-01-17 22:08
> I had to install ta-lib via brew

You shouldn't have to do this.

>  I also had to manually download all the .json files under store except config.json

Or this.

I have no reasonable explanation for either of these bugs. The code we wrote should solve each of these on its own...

**Comment by alichtman** [comment] 2019-01-18 03:56
@corsa We just pushed a fix for the json files not being generated properly. Try updating to v1.1.7

**Closed** 2019-01-18 03:59 UTC
Labels: bug, more-info-needed

**Comment by corsa** [comment] 2019-01-18 04:01
Cool, I uninstalled BitVision then reinstalled and the .json files were correctly added, and the UI is displaying data, so looks good.

**Comment by alichtman** [comment] 2019-01-18 04:03
Great to hear, @corsa.
