### ISSUE TITLE
allow copy & paste of API key credentials into login pop-up

### ISSUE THREAD

**Issue by sh4d0v1** [shobrook/BitVision#241] opened 2019-01-18 11:42 UTC
Since copy&paste of API key & secret is not possible, I typed the values several times by hand, always followed by the "check your connection or credentials" error.

So I copied the values into the config.json, and I had to set the "logged_in" flag to true, now the GUI acts like I was logged in, though I don't know if I really am. The portfolio stats still show zero though, so I guess I am not.

If my assumption, that the "username" is the BitStamp Customer-ID is correct, I don't know how to check if the login with the given credentials even is successful. Some feedback at this point would be helpful.

**Comment by shobrook** [comment] 2019-01-24 02:18
>Since copy&paste of API key & secret is not possible ...

Are you using Windows? On Mac, you can use CMD-V to paste. On Windows, you have to enable CTRL key shortcuts. You can read about how to do that [here.](https://www.howtogeek.com/howto/25590/how-to-enable-ctrlv-for-pasting-in-the-windows-command-prompt/)

>The portfolio stats still show zero though, so I guess I am not.

As mentioned on the README, the portfolio stats are still being implemented. Zero is the default value and won't be changed until the new release.

>If my assumption, that the "username" is the BitStamp Customer-ID is correct

That is correct. Thanks for pointing out that this isn't clear – I've updated the README accordingly.

>I don't know how to check if the login with the given credentials even is successful

Well, behind the scenes, the `logged_in` flag in `config.json` gets set to true when you've been successfully authenticated, but you manually set it to true. If you got the error pop-up when you submitted your credentials, and they were typed in correctly, then either you weren't connected to the internet or Bitstamp isn't recognizing your credentials.

**Comment by sh4d0v1** [comment] 2019-01-24 10:54
>Are you using Windows? On Mac, you can use CMD-V to paste. On Windows, you have to enable CTRL key shortcuts.

I am on Linux, but I just realized the problem isn't that pasting is prohibited somehow in the GUI, but that there are seemingly random spans of unresponsive behaviour in which the paste just makes no effect. Also I am observing node taking ~150% CPU of one thread in those spans of time, which can last some seconds to many minutes, in which the process is only possible to kill with -9.

So sorry, this issue can get closed, since its title is completely false.

>As mentioned on the README, the portfolio stats are still being implemented.

Sorry, must have read that over.

>an error panel will pop-up, in which case you either aren't connected to the internet or Bitstamp isn't recognizing your credentials

Since the error pops up even with copy-pasted login data and there is an internet connection (bitvision itself just fetched market data a few seconds before) BitStamp has to deny the credentials. So I checked fetching data with those API credentials with a python script, which works. So I am out of ideas here.

**Comment by shobrook** [comment] 2019-01-24 17:34
>but that there are seemingly random spans of unresponsive behaviour in which the paste just makes no effect. Also I am observing node taking ~150% CPU of one thread in those spans of time, which can last some seconds to many minutes, in which the process is only possible to kill with -9.

This might be a similar issue to #239. On some systems, when a child process is spawned to execute the Python scripts, it seems to hang and never exit. The blocking behavior is expected, though, but should only last a couple of seconds until the child process exits. I haven't figured out this error yet since I haven't been able to reproduce it. Sorry about this.

**Comment by shobrook** [comment] 2019-01-24 17:34
I'm going to close this issue and migrate discussion back to #239

**Closed by shobrook** 2019-01-24 17:34 UTC
